apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kustomize-poc-dev
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kustomize-poc
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/jane-delivery/akuity-kustomize-poc-config
          checkout:
          - branch: main
            path: ./src
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app/base/dev
          images:
          - image: ghcr.io/jane-delivery/akuity-poc-app
      - uses: kustomize-build
        config:
          path: ./src/app/base/dev
          outPath: ./src/dev/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./src
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./src
          targetBranch: main
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kustomize-poc-staging
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kustomize-poc
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/jane-delivery/akuity-kustomize-poc-config
          checkout:
          - branch: main
            path: ./src
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app/base/staging
          images:
          - image: ghcr.io/jane-delivery/akuity-poc-app
      - uses: kustomize-build
        config:
          path: ./src/app/base/staging
          outPath: ./src/staging/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./src/staging
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./src
          targetBranch: main
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: kustomize-poc-production
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kustomize-poc
    sources:
      stages:
      - staging
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/jane-delivery/akuity-kustomize-poc-config
          checkout:
          - branch: main
            path: ./src
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app/base/production
          images:
          - image: ghcr.io/jane-delivery/akuity-poc-app
      - uses: kustomize-build
        config:
          path: ./src/app/base/production
          outPath: ./src/production/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./src/production
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./src
          targetBranch: main