apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kustomize-poc
  namespace: kustomize-poc
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/jane-delivery/akuity-poc-app
      tagSelectionStrategy: semver
