apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-poc-staging
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kustomize-poc-staging
  template:
    metadata:
      labels:
        app: kustomize-poc-staging
    spec:
      containers:
      - image: ghcr.io/jane-delivery/akuity-poc-app:latest
        name: kustomize-poc
        ports:
        - name: http
          containerPort: 8080
